version: 1

formatters:
  standard:
    class: logging.Formatter
    format: '[%(levelname)-5s %(asctime)s] : %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  record:
    class: logging.Formatter
    format: '[%(levelname)-5s %(asctime)s] : %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  recordMsg:
    class: logging.Formatter
    format: '[%(levelname)-5s %(asctime)s] : --- record created ---'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    level: INFO
    filename: output_test.log
    mode: a
    encoding: utf-8
  record:
    class: logging.handlers.RotatingFileHandler
    formatter: record
    level: DEBUG
    filename: record.txt
    mode: w
    encoding: utf-8
  recordMsg:
    class: logging.StreamHandler
    formatter: recordMsg
    level: DEBUG

loggers:
  main:
    level: INFO
    handlers:
      - console
      # - file
  record:
    level: DEBUG
    handlers:
       - record
       - recordMsg
    


